name: Lesson Feedback
description: Share feedback, report issues, or suggest improvements for a lesson
title: "Lesson Feedback: "
labels:
  - lesson-feedback
  - education
  - needs-triage

body:
  - type: input
    id: lesson-name
    attributes:
      label: Lesson name
      description: Name of the lesson you are providing feedback for
      placeholder: e.g. Introduction to Open Source
    validations:
      required: true

  - type: dropdown
    id: feedback-type
    attributes:
      label: Feedback type
      description: What kind of feedback are you providing?
      options:
        - Bug / Error in content
        - Suggestion / Improvement
        - Quality / Clarity feedback
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feedback description
      description: >
        Please describe your feedback clearly.
        If reporting a bug, mention the section, heading, or link.
      placeholder: Write your feedback here...
    validations:
      required: true
